### ISSUE TITLE
Incorrect Source Code

### ISSUE THREAD

**Issue by PooyanRezaeipour** [msaadeghii/sparse-recovery#1]
Hello
You'll run into an error in running the source code("demo.m" file), because there is a mistake in the line of **116 of "IPP_SCAD.m"** file. (you can see here: https://github.com/msaadeghii/sparse-recovery/blob/master/SR_algs/IPP/IPP_SCAD.m)

**The aforementioned line must be modified to "x0 = x ;".**
As you can see in the line of **116 of "IPP_SCAD.m"** file in the below link: https://github.com/ghayem/IPP/blob/main/Algorithms/IPP_and_ISP/IPP_SCAD.m

sincerely yours

**Comment by msaadeghii** [comment]
Dear Pooyan,

Thanks a lot for pointing out this error. I just fixed it.

Best,
Mostafa
